"""circepy-phenotypes: efficient phenotyping template cohorts + proxy evaluation.

Import surface::

    from circepy_phenotypes import (
        FamilySpec, ResolvedFamily, resolve_family, TemplateFamilyExecutor,
        connect_backend, cs,
        evaluate, confusion_matrix, compute_metrics, rank_candidates,
    )
"""

from .backend import BackendConnection, connect_backend
from .cohorts import (
    TEMPLATE_SPECS,
    BuiltFamily,
    FamilySpec,
    ResolvedFamily,
    TemplateFamilyExecutor,
    TemplateSpec,
    build_all_expressions,
    build_atomic_groups,
    combine_criteria,
    combine_key_sets,
    concept_ids,
    condition_occurrence,
    cs,
    device_exposure,
    drug_exposure,
    event_ends_window,
    event_starts_window,
    intersect_all,
    intersect_keys,
    make_collapse_settings,
    make_end_strategy,
    make_entry_criteria,
    make_exclusion_criterion,
    make_f_criterion,
    make_multi_domain_criterion,
    measurement,
    observation,
    procedure,
    remove_ids,
    resolve_concept_set_overlaps,
    resolve_family,
    union_keys,
    visit,
)
from .evaluation import (
    ConfusionMatrix,
    EvaluationResult,
    Metrics,
    apply_demographics,
    build_demographic_group,
    compute_metrics,
    confusion_matrix,
    distinct_persons,
    domain_criteria,
    evaluate,
    evidence_expression,
    gold_standard_expression,
    rank_candidates,
    score,
)

__all__ = [
    "TEMPLATE_SPECS",
    "BackendConnection",
    "BuiltFamily",
    "ConfusionMatrix",
    "EvaluationResult",
    "FamilySpec",
    "Metrics",
    "ResolvedFamily",
    "TemplateFamilyExecutor",
    "TemplateSpec",
    "apply_demographics",
    "build_all_expressions",
    "build_atomic_groups",
    "build_demographic_group",
    "combine_criteria",
    "combine_key_sets",
    "compute_metrics",
    "concept_ids",
    "condition_occurrence",
    "confusion_matrix",
    "connect_backend",
    "cs",
    "device_exposure",
    "distinct_persons",
    "domain_criteria",
    "drug_exposure",
    "evaluate",
    "event_ends_window",
    "event_starts_window",
    "evidence_expression",
    "gold_standard_expression",
    "intersect_all",
    "intersect_keys",
    "make_collapse_settings",
    "make_end_strategy",
    "make_entry_criteria",
    "make_exclusion_criterion",
    "make_f_criterion",
    "make_multi_domain_criterion",
    "measurement",
    "observation",
    "procedure",
    "rank_candidates",
    "remove_ids",
    "resolve_concept_set_overlaps",
    "resolve_family",
    "score",
    "union_keys",
    "visit",
]
